### ISSUE TITLE
Json codec and enum fields

### ISSUE THREAD

**Issue by fr05t1k** [stanley-cheung/Protobuf-PHP#11]
I found specification for json mapping. Enums are represend as string, but codec trys decode/encode enum from integer. Is it correct or we need to fix this???

Spec:
https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by stanley-cheung** [comment]
This is a temporary fork of drslump/Protobuf-PHP. This seems like an issue you should take it to the upstream repo.

**Comment by fr05t1k** [comment]
ok, thanks
